### PR TITLE
Use canon type when converting return type to str

### PR DESCRIPTION
**Pull request by sudo-panda**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@sudo-panda do you plan to address the crashing xfail tests?

**Comment by sudo-panda** [comment]
Yes

**Comment by sudo-panda** [comment]
Depends on compiler-research/CppInterOp#107

**Comment by sudo-panda** [comment]
This can be merged now

**Comment by vgvassilev** [comment]
@sudo-panda I see the xfail tests crashing. Is that expected?

**Comment by sudo-panda** [comment]
I don't see any xfail tests crashing. Can you show where they are crashing?

**Comment by vgvassilev** [comment]
> I don't see any xfail tests crashing. Can you show where they are crashing?

Here: https://github.com/compiler-research/cppyy-backend/actions/runs/5495282689/jobs/10014577462?pr=76#step:16:921 ?

**Comment by sudo-panda** [comment]
@vgvassilev I am not sure what happened before, but I reran the tests, and now it's showing the same as I saw before. The xfails aren't crashing anymore, so you can merge this.

**Pull request merged**
