### PR TITLE
Remove ROOT meta dependency

### PR DESCRIPTION
**Pull request by sudo-panda**

### CODE REVIEW

**Review by vgvassilev — APPROVED** [review]
This looks reasonable approach to me. Let's merge it and then we can bring back stuff if we need it.

**Comment by vgvassilev** [comment]
@sudo-panda, can you resolve the conflicts of this PR?

**Comment by vgvassilev** [comment]
> @sudo-panda, can you resolve the conflicts of this PR?

ping.

**Comment by sudo-panda** [comment]
> > @sudo-panda, can you resolve the conflicts of this PR?

Yes, I am writing down the installation steps will do it after that

**Pull request merged**
